Разметка главной страницы
htmlacademy-adaptive/1893699-mishka-24 pull request #2
Opened 2021-11-28 08:32 UTC by maratabdulin

2021-11-28 20:32 UTC, Zakamsky requested changes
В целом хорошо, но есть путаница в методологии, давай доработаем.

2021-11-28 20:32 UTC, Zakamsky commented on Readme.md
> +* Наставник: [Алексей Елькин](https://htmlacademy.ru/profile/id604209).
отлично, спасибо!

2021-11-28 20:32 UTC, Zakamsky commented on source/img/sprite.svg
> +        d="M4.547 26.319c0-3.5-.3-6.9-.4-10.4v-1c0 .1.1.2.1.4.5 1.4 1.1 2.7 1.8 3.9.7 1.2 1.1 2.6 1.5 3.9-.2.2-.3.4-.2.6 0 .2.1.2.2.3.5.5 1.5.2 2.1 0 .2-.1.5-.2.7-.4.3-.2.7-.6.6-1 0-.1 0-.2-.1-.2.4-1
О ну круто, мы потом заставим гальп собирать спрайт, а если напомнишь, подскажу как из стилей вставлять картинку и менять ее цвета. Но уже после главы про спрайты и автоматизацию.

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
А вот тут ты кажется собрался все бэдпрактисы адаптивной верстки. Это даже в валидаторе подсветится...
Зачем запрещать пользователю зум на мобильных устройствах? а если у него со зрением проблемы?
Достаточно указать `width=device-width, initial-scale=1.0` остальное где то за гранью добра и зла...
upd: хотя технически это не ошибка конечно.

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +  </a>
Странно что в подвале ты добавил лого в разметку, а здесь нет... Вообще лого это очень важная часть сайта, это ведь лицо брэнда, в него деньги вложены... в общем лого не просто по хорошему надо добавить в разметку, надо бы еще ему альт хороший написать что бы картинка индексировалась и продвигала сайт в поиске по картинкам. А если у нас не img а svg используется по какой то причине (В мишке кажется только прозрачность меняется), то стоит имитировать альт с помощью ролей и ариа атрибутов. (Об  этом будет позже в демках)

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +    <ul class="user-list">
тут два момента меня смущают:
1. у нас нет блока `.header` может ты `.page-header` имел ввиду?
2. `<nav>` это главная навигация, если мы используем несколько таких тэгов на странице стоит разметить какой из них САМЫЙ главный, с помощью ролей. Но кажется тут можно обойтись одним `<nav>` в котором лежат два списка (или даже один список, но если тебе удобнее сделать два, это тоже нормально.)

В общем давай так - ошибку методологии надо исправить, а про навигации и разметку можно еще подумать, пока будешь стилизовать, никуда они от нас не убегут.

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +  <button class="main-nav__toggle" type="button">
ой, чуть не пропустил, это элемент какого блока?

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +      </li>
а что делают эти кнопки при нажатии? 
(если нет переходов, то откуда навигация?)
в общем у нас нет никаких попапов с поиском или корзиной, кажется это просто ссылки на страницу с поиском и страницу корзины. А если мы поиск сделаем кнопкой нас еще чего доброго на защите заставят форму к ней приделать....

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +        <a href="#" class="category__link">
очепяточка опять, у нас ведь нет такого блока, может это `.main-header__link`?

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +        </li>
а зачем ты эти иконки тащишь в разметку? разве это контентная графика? или нам нужно их цвет менять? 
лучше все же сделать тут фоновые изображения, можно как псевдоэлементы. 
После 8й главы даже придумаем как спрайт использовать.

2021-11-28 20:32 UTC, Zakamsky commented on source/index.html
> +    </svg>
а это элемент которого блока?

2021-11-29 04:27 UTC, maratabdulin commented on source/img/sprite.svg
> +        d="M4.547 26.319c0-3.5-.3-6.9-.4-10.4v-1c0 .1.1.2.1.4.5 1.4 1.1 2.7 1.8 3.9.7 1.2 1.1 2.6 1.5 3.9-.2.2-.3.4-.2.6 0 .2.1.2.2.3.5.5 1.5.2 2.1 0 .2-.1.5-.2.7-.4.3-.2.7-.6.6-1 0-.1 0-.2-.1-.2.4-1
Как вставлять картинки из стилей с возможностью менять цвета, ещё не знаю)

2021-11-29 04:28 UTC, maratabdulin commented on source/index.html
> +        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
Это поправлю

2021-11-29 04:30 UTC, maratabdulin commented on source/index.html
> +  </a>
Там просто логотип меняется с изменением устройства. И я подумал вставлять картинку через стили. А вот в footer логотип один и тот, но меняет цвет при hover  и прочее.

2021-11-29 04:34 UTC, maratabdulin commented on source/index.html
> +    <ul class="user-list">
Header исправлю на page-header. А как задать главную роль одному из nav. Я всё-таки хотел 2  nav  независимо сделать. Чтобы в будущем их было проще по странице перемешать

2021-11-29 04:34 UTC, maratabdulin commented on source/index.html
> +      </li>
Согласен кнопки надо изменить на ссылки

2021-11-29 04:36 UTC, maratabdulin commented on source/index.html
> +  <button class="main-nav__toggle" type="button">
Так это page-header__toggle надо поправить

2021-11-29 04:37 UTC, maratabdulin commented on source/index.html
> +        <a href="#" class="category__link">
Это поправлю

2021-11-29 04:52 UTC, maratabdulin commented on source/index.html
> +        </li>
Иконки уберу

2021-11-29 04:59 UTC, maratabdulin commented on source/index.html
> +    </svg>
поправлю

2021-11-29 07:56 UTC, Zakamsky commented on source/img/sprite.svg
> +        d="M4.547 26.319c0-3.5-.3-6.9-.4-10.4v-1c0 .1.1.2.1.4.5 1.4 1.1 2.7 1.8 3.9.7 1.2 1.1 2.6 1.5 3.9-.2.2-.3.4-.2.6 0 .2.1.2.2.3.5.5 1.5.2 2.1 0 .2-.1.5-.2.7-.4.3-.2.7-.6.6-1 0-.1 0-.2-.1-.2.4-1
Это нормально. Способ не простой. Я тут просто радуюсь что ты уже знаком со спрайтами.

2021-11-29 08:01 UTC, Zakamsky commented on source/index.html
> +  </a>
Лучше все же отталкиваться от того контентное изображение или оформительское. И если спрайт все еще повод использовать тэг свг, то не добавить контент в разметку из за того что проще управлять стилями... Может просто еще не хватает понимания как управлять видимостью элементов из стилей...
Это как раз причина, по которой закрыли серым другие экраны. Попробуй представить что мы верстаем только мобилку. А если там что то будет сильно отличаться - подскажут как это реализуется.

2021-11-29 08:10 UTC, Zakamsky commented on source/index.html
> +    <ul class="user-list">
На вскидку не скажу. Кажется роль main нужна. Попробуй поискать в гугл по "несколько nav на одной странице" или мне в чате напомни вечером.

2021-11-29 08:10 UTC, merged