Разметка внутренних страниц
htmlacademy-adaptive/1893699-mishka-24 pull request #3
Opened 2021-11-28 12:04 UTC by maratabdulin

2021-11-29 23:17 UTC, Zakamsky requested changes
Очень добротно сделан БЭМ, но будь пожалуйста чуть внимательнее, ошибки несерьезные, но их много и форму надо бы поправить, давай доработаем, прежде чем начинать новую тему.

2021-11-29 23:17 UTC, Zakamsky commented on source/catalog.html
> +    <svg class="category__icon" width="32" height="22">
и еще таких `svg` парочка...

2021-11-29 23:17 UTC, Zakamsky commented on source/form.html
> +          <li class="form-oder__filter-item">
Единственное нарекание по БЭМ на этой странице, и это не ошибка БЭМа, это скорее невнимательность (я бы советовал использовать для имен блока копи-паст или еммет)
`form-order` -> `form-oder`

2021-11-29 23:17 UTC, Zakamsky commented on source/form.html
> +          <input class="filter-contact__input" type="tel" name="user-tel" placeholder="+7 ХХХ ХХХ ХХ ХХ*" pattern="[0-9]{3}-[0-9]{3}-[0-9]{2}-[0-9]{2}" required>
честно говоря, я бы за такое отругал. Во первых, мой совет на будущее, лучше использовать подобную валидацию по паттерну из скриптов и показывать сообщение с нужным форматом, как только пользователь начал вводить номер он не видит плэйсхолдер. 
(можно еще использовать штмл с текстом подсказкой и показывать его если ввод не валиден, но это не должно бы ломать дизайн)

Ну и то что меня больше всего расстроило в это строке:
плэйсхолдер намекает на формат номера - `+7 ХХХ ХХХ ХХ ХХ`
а паттерн пропускает только `ХХХ-ХХХ-ХХ-ХХ`
т.е. пользователь который не умеет смотреть в дефтулз просто не сможет угадать нужный формат... и мы потеряем клиентов. 
В общем надо или поправить паттерн под макет, или убрать его....

2021-11-29 23:17 UTC, Zakamsky commented on source/form.html
> +          <input class="filter-contact__input" type="email" name="user-email" placeholder="Ваш Email*" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2, 4}$" required>
тут паттерн лишний, браузер сам провалидирует поле email и не допустит не валидный ввод.

2021-11-29 23:17 UTC, Zakamsky commented on source/form.html
> +          <textarea class="filter-additional__input" name="additional">Опишите все ваши пожелания к заказу</textarea>
Этот текст прямо лежит в поле ввода, это означает что во первых пользователь должен будет его удалить, перед тем как ввести что то свое. Во вторых, если ему будет лень - этот текст улетит на сервер. 
Нельзя ил как то не добавлять лишней работы пользователю и серверу? может перенести этот текст в плэйсхолдер?

2021-11-29 23:17 UTC, Zakamsky commented on source/form.html
> +    <svg class="category__icon" width="27" height="35">
и еще раз странный элемент несуществующего блока. проверь индекс тоже.

2021-11-30 05:25 UTC, maratabdulin commented on source/catalog.html
> +        <h3 class="product-card__title">Зайчик-попрыгайчик</h3>
Да, добавлю заголовок и дивы поправлю на артиклы

2021-11-30 05:25 UTC, maratabdulin commented on source/catalog.html
> +        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
так так, сейчас поправлю)

2021-11-30 05:29 UTC, maratabdulin commented on source/catalog.html
> +        <svg class="main-header__icon" width="20" height="19">
Да и в форме тоже пользовался заготовками с прошлого проекта)

2021-11-30 05:32 UTC, maratabdulin commented on source/catalog.html
> +    <svg class="category__icon" width="32" height="22">
Поправил

2021-11-30 05:33 UTC, maratabdulin commented on source/form.html
> +          <li class="form-oder__filter-item">
так, да, поправил

2021-11-30 05:34 UTC, maratabdulin commented on source/form.html
> +          <li class="form-oder__filter-item">
С эмметом для БЭМ я еще не знаком, надо изучить

2021-11-30 05:36 UTC, maratabdulin commented on source/form.html
> +          <input class="filter-contact__input" type="tel" name="user-tel" placeholder="+7 ХХХ ХХХ ХХ ХХ*" pattern="[0-9]{3}-[0-9]{3}-[0-9]{2}-[0-9]{2}" required>
Пока уберу паттерн, не настолько хорошо разобрался.

2021-11-30 05:36 UTC, maratabdulin commented on source/form.html
> +          <input class="filter-contact__input" type="email" name="user-email" placeholder="Ваш Email*" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2, 4}$" required>
Уберу паттерн

2021-11-30 05:37 UTC, maratabdulin commented on source/form.html
> +          <textarea class="filter-additional__input" name="additional">Опишите все ваши пожелания к заказу</textarea>
Да, перенесу текст в плейсхолдер

2021-11-30 05:40 UTC, maratabdulin commented on source/form.html
> +    <svg class="category__icon" width="27" height="35">
Поправил в каталоге и форме

2021-11-30 23:24 UTC, merged